//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agentes_Fisico
    {
        public Agentes_Fisico()
        {
            this.Detalle_Plan_Tratamiento = new HashSet<Detalle_Plan_Tratamiento>();
            this.Tipo_Diagnostico = new HashSet<Tipo_Diagnostico>();
        }
    
        public int nIdAgenteFisico { get; set; }
        public string cDescripTipoAge { get; set; }
    
        public virtual ICollection<Detalle_Plan_Tratamiento> Detalle_Plan_Tratamiento { get; set; }
        public virtual ICollection<Tipo_Diagnostico> Tipo_Diagnostico { get; set; }
    }
}
