//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alta_Tratamiento
    {
        public int nAltaTratamientoId { get; set; }
        public Nullable<int> nDiagnosticoId { get; set; }
        public string cRecomendacion { get; set; }
    
        public virtual Diagnostico Diagnostico { get; set; }
    }
}
