//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public Ambiente()
        {
            this.Ambiente_Especialidad = new HashSet<Ambiente_Especialidad>();
            this.Ambiente_Profesional = new HashSet<Ambiente_Profesional>();
            this.CitaAdicionals = new HashSet<CitaAdicional>();
            this.Disponibilidad_Medica = new HashSet<Disponibilidad_Medica>();
            this.HorarioProgramas = new HashSet<HorarioPrograma>();
            this.Reserva_Cita = new HashSet<Reserva_Cita>();
            this.Detalle_Plan_Servicio = new HashSet<Detalle_Plan_Servicio>();
            this.Equipo_Ambiente = new HashSet<Equipo_Ambiente>();
            this.Orden_Intervencion = new HashSet<Orden_Intervencion>();
        }
    
        public int nAmbienteId { get; set; }
        public Nullable<int> nTipoAmbienteId { get; set; }
        public string cAmbienteNombre { get; set; }
        public Nullable<int> nAmbienteRelacionId { get; set; }
        public string cEliminado { get; set; }
    
        public virtual ICollection<Ambiente_Especialidad> Ambiente_Especialidad { get; set; }
        public virtual ICollection<Ambiente_Profesional> Ambiente_Profesional { get; set; }
        public virtual ICollection<CitaAdicional> CitaAdicionals { get; set; }
        public virtual ICollection<Disponibilidad_Medica> Disponibilidad_Medica { get; set; }
        public virtual ICollection<HorarioPrograma> HorarioProgramas { get; set; }
        public virtual ICollection<Reserva_Cita> Reserva_Cita { get; set; }
        public virtual ICollection<Detalle_Plan_Servicio> Detalle_Plan_Servicio { get; set; }
        public virtual ICollection<Equipo_Ambiente> Equipo_Ambiente { get; set; }
        public virtual ICollection<Orden_Intervencion> Orden_Intervencion { get; set; }
    }
}
