//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id { get; set; }
        public Nullable<int> Fecha_CIta { get; set; }
        public Nullable<int> Hora_Cita { get; set; }
        public string observacion { get; set; }
        public int Cronograma_Profesionalid { get; set; }
        public int Profesionalid { get; set; }
        public int Pacienteid { get; set; }
        public int Plan_Servicioid { get; set; }
    }
}
