//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id { get; set; }
        public Nullable<int> Fecha_CIta { get; set; }
        public Nullable<int> Hora_Cita { get; set; }
        public string observacion { get; set; }
        public int Cronograma_Profesionalid { get; set; }
        public int Profesionalid { get; set; }
        public int Pacienteid { get; set; }
        public int Plan_Servicioid { get; set; }
    }
}
