//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_Profesional
    {
        public Cronograma_Profesional()
        {
            this.Cronograma_ProfesionalDetalle = new HashSet<Cronograma_ProfesionalDetalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Nro_Sesiones { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public int Profesionalid { get; set; }
    
        public virtual ICollection<Cronograma_ProfesionalDetalle> Cronograma_ProfesionalDetalle { get; set; }
    }
}
