//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_Servicio
    {
        public Cronograma_Servicio()
        {
            this.Equipo = new HashSet<Equipo>();
            this.Sala = new HashSet<Sala>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Hora_Fin { get; set; }
    
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual ICollection<Sala> Sala { get; set; }
    }
}
