//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_Especialista
    {
        public Cronograma_Especialista()
        {
            this.Cronograma_EspecialistaDetalle = new HashSet<Cronograma_EspecialistaDetalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Nro_Sesiones { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public int Especialistaid { get; set; }
    
        public virtual ICollection<Cronograma_EspecialistaDetalle> Cronograma_EspecialistaDetalle { get; set; }
        public virtual Especialista Especialista { get; set; }
    }
}
