//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_Servicio
    {
        public Cronograma_Servicio()
        {
            this.Equipo = new HashSet<Equipo>();
            this.Sala = new HashSet<Sala>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Hora_Fin { get; set; }
    
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual ICollection<Sala> Sala { get; set; }
    }
}
