//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_Terapista
    {
        public Cronograma_Terapista()
        {
            this.Cronograma_TerapistaDetalle = new HashSet<Cronograma_TerapistaDetalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Nro_Sesiones { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public int Terapistaid { get; set; }
    
        public virtual ICollection<Cronograma_TerapistaDetalle> Cronograma_TerapistaDetalle { get; set; }
        public virtual Terapista Terapista { get; set; }
    }
}
