//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_Terapista
    {
        public Cronograma_Terapista()
        {
            this.Cronograma_TerapistaDetalle = new HashSet<Cronograma_TerapistaDetalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Nro_Sesiones { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public int Terapistaid { get; set; }
    
        public virtual ICollection<Cronograma_TerapistaDetalle> Cronograma_TerapistaDetalle { get; set; }
        public virtual Terapista Terapista { get; set; }
    }
}
