//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Historia_Clinica
    {
        public int nDetalleHistoriaClinicaId { get; set; }
        public Nullable<int> nHistoriaClinicaId { get; set; }
        public string cAntecedentes { get; set; }
    
        public virtual Historia_Clinica Historia_Clinica { get; set; }
    }
}
