//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Plan_Tratamiento
    {
        public int nIdDetallePlanTratamiento { get; set; }
        public int Plan_Tratamiento_nIdPlanTratamiento { get; set; }
        public int Agentes_Fisico_nIdAgenteFisico { get; set; }
    
        public virtual Agentes_Fisico Agentes_Fisico { get; set; }
        public virtual Plan_Tratamiento Plan_Tratamiento { get; set; }
    }
}
