//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Plan_Servicio
    {
        public int nIdDetallePlanServicio { get; set; }
        public Nullable<System.DateTime> dFecha { get; set; }
        public string cEstado { get; set; }
        public int Sala_nIdSala { get; set; }
        public int Turno_idTurno { get; set; }
        public int Cita_nIdCita { get; set; }
        public int Plan_de_Servicio_nIdPlanServicio { get; set; }
        public int Profesional_nIdProfesional { get; set; }
        public int Tipo_Detalle_Servicio_nIdTipo { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Plan_de_Servicio Plan_de_Servicio { get; set; }
        public virtual Profesional Profesional { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Tipo_Detalle_Servicio Tipo_Detalle_Servicio { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
