//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public Diagnostico()
        {
            this.Altas = new HashSet<Alta>();
            this.Plan_Tratamiento = new HashSet<Plan_Tratamiento>();
        }
    
        public int nIdDiagnostico { get; set; }
        public Nullable<System.DateTime> dFEcha { get; set; }
        public string cDetalleDiag { get; set; }
        public string cEstado { get; set; }
        public int Paciente_nIdPaciente { get; set; }
        public int Tipo_Diagnostico_nIdTipoDiagnostico { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<Alta> Altas { get; set; }
        public virtual Tipo_Diagnostico Tipo_Diagnostico { get; set; }
        public virtual ICollection<Plan_Tratamiento> Plan_Tratamiento { get; set; }
    }
}
