//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Diagnostico1 { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<System.DateTime> FechaIniTerapia { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<int> Nro_Sesiones { get; set; }
        public string observacion { get; set; }
        public int Pacienteid { get; set; }
        public int Profesionalid { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
