//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.Salas = new HashSet<Sala>();
        }
    
        public int nIdEquipo { get; set; }
        public string cNomEquipo { get; set; }
    
        public virtual ICollection<Sala> Salas { get; set; }
    }
}
