//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.Cronograma_Servicio = new HashSet<Cronograma_Servicio>();
        }
    
        public int id { get; set; }
        public Nullable<int> Nro_Serie { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string observacion { get; set; }
    
        public virtual ICollection<Cronograma_Servicio> Cronograma_Servicio { get; set; }
    }
}
