//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        public Especialista()
        {
            this.Cronograma_Especialista = new HashSet<Cronograma_Especialista>();
            this.Diagnostico = new HashSet<Diagnostico>();
        }
    
        public int id { get; set; }
        public Nullable<int> Doc_Identidad { get; set; }
        public string Nombre { get; set; }
        public string Ape_Paterno { get; set; }
        public string Ape_Materno { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Nro_Colegiatura { get; set; }
        public int TipoEspecialidadid { get; set; }
        public int TipoDocumentoid { get; set; }
    
        public virtual ICollection<Cronograma_Especialista> Cronograma_Especialista { get; set; }
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
        public virtual TipoEspecialidad TipoEspecialidad { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
