//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad_Prestacion
    {
        public int nEspPrestacionId { get; set; }
        public Nullable<int> nPrestacionId { get; set; }
        public Nullable<int> nEspecialidadId { get; set; }
    }
}
