//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha_Evolucion
    {
        public int id { get; set; }
        public int numero_sesion { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public int Terapistaid { get; set; }
        public int Diagnosticoid { get; set; }
    
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual Terapista Terapista { get; set; }
    }
}
