//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha_Evolucion
    {
        public int id { get; set; }
        public int numero_sesion { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public int Terapistaid { get; set; }
        public int Diagnosticoid { get; set; }
    
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual Terapista Terapista { get; set; }
    }
}
