//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_Clinica
    {
        public Historia_Clinica()
        {
            this.Detalle_Historia_Clinica = new HashSet<Detalle_Historia_Clinica>();
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int nHistoriaClinicaId { get; set; }
        public string cNroHistoriaClinica { get; set; }
    
        public virtual ICollection<Detalle_Historia_Clinica> Detalle_Historia_Clinica { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
