//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioPrograma
    {
        public int nHorarioProgramaId { get; set; }
        public Nullable<int> nProgMedicaId { get; set; }
        public Nullable<int> nAmbienteId { get; set; }
        public Nullable<System.DateTime> dFecha { get; set; }
        public Nullable<System.TimeSpan> dHoraInicio { get; set; }
        public Nullable<System.TimeSpan> dHoraFin { get; set; }
        public Nullable<int> nEstadoId { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        public virtual Programacion_Medica Programacion_Medica { get; set; }
    }
}
