//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioMedico
    {
        public HorarioMedico()
        {
            this.Disponibilidad_Medica = new HashSet<Disponibilidad_Medica>();
        }
    
        public int nHorarioMedicoId { get; set; }
        public Nullable<int> nProfesionalId { get; set; }
        public Nullable<System.DateTime> dFechaInicio { get; set; }
        public Nullable<System.DateTime> dFechaFin { get; set; }
        public Nullable<int> nEstadoId { get; set; }
    
        public virtual ICollection<Disponibilidad_Medica> Disponibilidad_Medica { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
