//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        public int nMaestroId { get; set; }
        public string cMaestroDescripcion { get; set; }
        public Nullable<int> nTablaId { get; set; }
        public Nullable<int> nItemId { get; set; }
        public string cEliminado { get; set; }
    }
}
