//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Medica
    {
        public Orden_Medica()
        {
            this.Orden_Intervencion = new HashSet<Orden_Intervencion>();
        }
    
        public int nOrdenMedId { get; set; }
        public Nullable<System.DateTime> dFechaEmision { get; set; }
        public Nullable<System.DateTime> dFechaVigencia { get; set; }
        public Nullable<int> nPacienteId { get; set; }
        public Nullable<int> nTipoIntervencionId { get; set; }
        public Nullable<int> nEstado { get; set; }
    
        public virtual ICollection<Orden_Intervencion> Orden_Intervencion { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Tipo_Intervencion Tipo_Intervencion { get; set; }
    }
}
