//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Intervencion
    {
        public Orden_Intervencion()
        {
            this.Requisitos_Orden_Int = new HashSet<Requisitos_Orden_Int>();
        }
    
        public int nOrdenIntervencionId { get; set; }
        public Nullable<int> nOrdenMedId { get; set; }
        public Nullable<System.DateTime> dFecha { get; set; }
        public Nullable<int> nAmbienteId { get; set; }
        public Nullable<int> nEstadoId { get; set; }
        public string cEliminado { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        public virtual Orden_Medica Orden_Medica { get; set; }
        public virtual ICollection<Requisitos_Orden_Int> Requisitos_Orden_Int { get; set; }
    }
}
