//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Historia_Clinica = new HashSet<Historia_Clinica>();
            this.Citas = new HashSet<Cita>();
            this.Diagnosticoes = new HashSet<Diagnostico>();
        }
    
        public int nIdPaciente { get; set; }
        public int Tipo_Documento_nIdTipoDocumento { get; set; }
        public string nNroDocumento { get; set; }
        public string cNomPaciente { get; set; }
        public string cApePaciente { get; set; }
        public Nullable<int> nEdad { get; set; }
        public string cSexo { get; set; }
        public string cNroTelefono { get; set; }
        public string cEmail { get; set; }
    
        public virtual ICollection<Historia_Clinica> Historia_Clinica { get; set; }
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
    }
}
