//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Diagnostico = new HashSet<Diagnostico>();
            this.Historia_Clinica = new HashSet<Historia_Clinica>();
        }
    
        public int id { get; set; }
        public string Doc_Identidad { get; set; }
        public string Nombre { get; set; }
        public string Ape_Materno { get; set; }
        public string Ape_Paterno { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
        public string Grupo_Sanguineo { get; set; }
        public int TipoDocumentoid { get; set; }
    
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
        public virtual ICollection<Historia_Clinica> Historia_Clinica { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
