//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Pacientes = new HashSet<Paciente>();
            this.Profesionals = new HashSet<Profesional>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int nPersonaId { get; set; }
        public string cNombres { get; set; }
        public string cApePaterno { get; set; }
        public string cApeMaterno { get; set; }
        public Nullable<int> nEdad { get; set; }
        public string cSexo { get; set; }
        public Nullable<System.DateTime> dFechaNacimiento { get; set; }
        public string cNroTelefono { get; set; }
        public string cEmail { get; set; }
        public Nullable<int> nTipoDocumentoId { get; set; }
        public string cNroDocumento { get; set; }
    
        public virtual ICollection<Paciente> Pacientes { get; set; }
        public virtual ICollection<Profesional> Profesionals { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
