//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_de_Servicio
    {
        public Plan_de_Servicio()
        {
            this.Detalle_Plan_Servicio = new HashSet<Detalle_Plan_Servicio>();
        }
    
        public int nIdPlanServicio { get; set; }
        public string cAño { get; set; }
        public string cMes { get; set; }
        public string cEstado { get; set; }
        public int nNroDiasgnoticos { get; set; }
        public Nullable<int> nNroSesiones { get; set; }
        public Nullable<int> nNroPacientes { get; set; }
    
        public virtual ICollection<Detalle_Plan_Servicio> Detalle_Plan_Servicio { get; set; }
    }
}
