//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Tratamiento
    {
        public Plan_Tratamiento()
        {
            this.Detalle_Plan_Tratamiento = new HashSet<Detalle_Plan_Tratamiento>();
            this.Ficha_Evolucion = new HashSet<Ficha_Evolucion>();
        }
    
        public int nIdPlanTratamiento { get; set; }
        public Nullable<int> nNroTerapias { get; set; }
        public Nullable<int> nVecesPorSemana { get; set; }
        public int Diagnostico_nIdDiagnostico { get; set; }
    
        public virtual ICollection<Detalle_Plan_Tratamiento> Detalle_Plan_Tratamiento { get; set; }
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual ICollection<Ficha_Evolucion> Ficha_Evolucion { get; set; }
    }
}
