//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanTratamiento_Agente
    {
        public int nPlanTratamientoAgenteId { get; set; }
        public Nullable<int> nPlanTratamientoId { get; set; }
        public Nullable<int> nTipoAgenteFisicoId { get; set; }
    
        public virtual Plan_Tratamiento Plan_Tratamiento { get; set; }
    }
}
