//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Tratamiento
    {
        public Plan_Tratamiento()
        {
            this.Detalle_Plan_Tratamiemto = new HashSet<Detalle_Plan_Tratamiemto>();
            this.PlanTratamiento_Agente = new HashSet<PlanTratamiento_Agente>();
        }
    
        public int nPlanTratamientoId { get; set; }
        public Nullable<int> nNroTerapias { get; set; }
        public Nullable<int> nVecesSemana { get; set; }
        public Nullable<int> nDiagnosticoId { get; set; }
    
        public virtual ICollection<Detalle_Plan_Tratamiemto> Detalle_Plan_Tratamiemto { get; set; }
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual ICollection<PlanTratamiento_Agente> PlanTratamiento_Agente { get; set; }
    }
}
