//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        public Profesional()
        {
            this.Detalle_Plan_Servicio = new HashSet<Detalle_Plan_Servicio>();
        }
    
        public int nIdProfesional { get; set; }
        public string cNombre { get; set; }
        public int Tipo_Profesional_nIdTipoProfe { get; set; }
    
        public virtual ICollection<Detalle_Plan_Servicio> Detalle_Plan_Servicio { get; set; }
        public virtual Tipo_Profesional Tipo_Profesional { get; set; }
    }
}
