//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesionalPlan
    {
        public int nProfesionalPlanId { get; set; }
        public Nullable<int> nDetPlanServicioId { get; set; }
        public Nullable<int> nProfesionalId { get; set; }
    
        public virtual Profesional Profesional { get; set; }
        public virtual Detalle_Plan_Servicio Detalle_Plan_Servicio { get; set; }
    }
}
