//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion_Medica
    {
        public Programacion_Medica()
        {
            this.HorarioProgramas = new HashSet<HorarioPrograma>();
        }
    
        public int nProgMedicaId { get; set; }
        public Nullable<int> nProfesionalId { get; set; }
        public Nullable<System.DateTime> dFechaInicio { get; set; }
        public Nullable<System.DateTime> dFechaFin { get; set; }
        public Nullable<int> nEstadoId { get; set; }
    
        public virtual ICollection<HorarioPrograma> HorarioProgramas { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
