//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Cita
    {
        public int nReservaCitaId { get; set; }
        public Nullable<int> nPacienteId { get; set; }
        public Nullable<int> nAmbienteId { get; set; }
        public Nullable<int> nEspecialidadId { get; set; }
        public Nullable<int> nProfesionalId { get; set; }
        public Nullable<int> nPrestacionId { get; set; }
        public Nullable<System.DateTime> dFecha { get; set; }
        public Nullable<System.TimeSpan> dHora { get; set; }
        public Nullable<System.DateTime> dFechaRegistro { get; set; }
        public Nullable<int> nEstadoId { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
