//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RPRehabilitacionEntities : DbContext
    {
        public RPRehabilitacionEntities()
            : base("name=RPRehabilitacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alta> Altas { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Cronograma_Profesional> Cronograma_Profesional { get; set; }
        public virtual DbSet<Cronograma_ProfesionalDetalle> Cronograma_ProfesionalDetalle { get; set; }
        public virtual DbSet<Cronograma_Servicio> Cronograma_Servicio { get; set; }
        public virtual DbSet<Diagnotico> Diagnoticoes { get; set; }
        public virtual DbSet<Equipo> Equipoes { get; set; }
        public virtual DbSet<Ficha_Evolucion> Ficha_Evolucion { get; set; }
        public virtual DbSet<Historia_Clinica> Historia_Clinica { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Profesional> Profesionals { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
    
        public virtual ObjectResult<Nullable<int>> usp_login()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_login");
        }
    }
}
