//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public Sala()
        {
            this.Cronograma_Servicio = new HashSet<Cronograma_Servicio>();
        }
    
        public int id { get; set; }
        public Nullable<int> Nro { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public string Especialidad { get; set; }
    
        public virtual ICollection<Cronograma_Servicio> Cronograma_Servicio { get; set; }
    }
}
