//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapista
    {
        public Terapista()
        {
            this.Cronograma_Terapista = new HashSet<Cronograma_Terapista>();
            this.Ficha_Evolucion = new HashSet<Ficha_Evolucion>();
        }
    
        public int id { get; set; }
        public Nullable<int> Doc_Identidad { get; set; }
        public string Nombre { get; set; }
        public string Ape_Paterno { get; set; }
        public string Ape_Materno { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Nro_Colegiatura { get; set; }
        public int TipoDocumentoid { get; set; }
    
        public virtual ICollection<Cronograma_Terapista> Cronograma_Terapista { get; set; }
        public virtual ICollection<Ficha_Evolucion> Ficha_Evolucion { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
