//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Profesional
    {
        public Tipo_Profesional()
        {
            this.Profesionals = new HashSet<Profesional>();
        }
    
        public int nIdTipoProfe { get; set; }
        public string cDescTipo { get; set; }
    
        public virtual ICollection<Profesional> Profesionals { get; set; }
    }
}
