//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEspecialidad
    {
        public TipoEspecialidad()
        {
            this.Especialista = new HashSet<Especialista>();
        }
    
        public int id { get; set; }
        public string Especialidad { get; set; }
    
        public virtual ICollection<Especialista> Especialista { get; set; }
    }
}
