//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Diagnostico
    {
        public Tipo_Diagnostico()
        {
            this.Diagnosticoes = new HashSet<Diagnostico>();
            this.Agentes_Fisico = new HashSet<Agentes_Fisico>();
        }
    
        public int nIdTipoDiagnostico { get; set; }
        public string cNombreDiagnostico { get; set; }
    
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        public virtual ICollection<Agentes_Fisico> Agentes_Fisico { get; set; }
    }
}
