//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Documento
    {
        public Tipo_Documento()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int nIdTipoDocumento { get; set; }
        public string nCodDoc { get; set; }
        public string cDescTipoDoc { get; set; }
    
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
