//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Intervencion
    {
        public Tipo_Intervencion()
        {
            this.Orden_Medica = new HashSet<Orden_Medica>();
            this.Requisitos = new HashSet<Requisito>();
        }
    
        public int nTipoIntervencionId { get; set; }
        public string cTipoIntNombre { get; set; }
    
        public virtual ICollection<Orden_Medica> Orden_Medica { get; set; }
        public virtual ICollection<Requisito> Requisitos { get; set; }
    }
}
