//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int id { get; set; }
        public string Documento { get; set; }
    
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
