//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.Especialista = new HashSet<Especialista>();
            this.Paciente = new HashSet<Paciente>();
            this.Terapista = new HashSet<Terapista>();
        }
    
        public int id { get; set; }
        public string Documento { get; set; }
    
        public virtual ICollection<Especialista> Especialista { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual ICollection<Terapista> Terapista { get; set; }
    }
}
