//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Rehabilitacion.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int nUsuarioId { get; set; }
        public Nullable<int> nPersonaId { get; set; }
        public string cUsuarioLogin { get; set; }
        public string cContrasena { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
